<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MININT-ADD5E5S" name="Clasno.Negative_tests.LoginInClasno" tests="1" failures="1" timestamp="9 Aug 2016 09:21:14 GMT" time="12.151" errors="0">
  <testcase name="LoginInClasno" time="12.151" classname="Clasno.Negative_tests.LoginInClasno">
    <failure type="java.lang.AssertionError" message="expected [Р’РѕР№С‚Рё РЅРµ СѓРґР°Р»РѕСЃСЊ. РќРµРІРµСЂРЅС‹Р№ e-mail РёР»Рё РїР°СЂРѕР»СЊ.] but found [Войти не удалось. Неверный e-mail или пароль.]">
      <![CDATA[java.lang.AssertionError: expected [Р’РѕР№С‚Рё РЅРµ СѓРґР°Р»РѕСЃСЊ. РќРµРІРµСЂРЅС‹Р№ e-mail РёР»Рё РїР°СЂРѕР»СЊ.] but found [Войти не удалось. Неверный e-mail или пароль.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Clasno.Negative_tests.LoginInClasno.LoginInClasno(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- LoginInClasno -->
</testsuite> <!-- Clasno.Negative_tests.LoginInClasno -->
